# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
  schedule:
    - cron: '58 18 * * *' 
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin' 
        architecture: x64

    - name: Make gradlew runnable
      run: |
        chmod +x gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Archive JAR Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: jar-artifact
        path: ./build/libs/CMRIT2025Leaderboard-1.0-SNAPSHOT.jar

  check:
    needs: build

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Check all files
      run: |
        ls -R
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin' 
        architecture: x64

    - name: Download JAR Artifact
      uses: actions/download-artifact@v4.0.0
      with:
        name: jar-artifact
        path: ./build/libs/

    - name: Run JAR File
      run: |
        java -jar ./build/libs/CMRIT2025Leaderboard-1.0-SNAPSHOT.jar all

    - name: Archive all files
      uses: actions/upload-artifact@v4.0.0
      with:
        name: all-files
        path: ./