name: Java, Python CI with Gradle for LeetCode

on:
  workflow_dispatch:
  push:
    branches:
      - py-tests

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4.1.1
      with:
        ref: ${{ github.ref }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin' 
        architecture: x64

    - name: Make gradlew runnable
      run: |
        chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    
    - name: Execute Gradle build
      run: ./gradlew build
      
    - name: Archive JAR Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: jar-artifact
        path: ./build/libs/CMRIT2025Leaderboard-1.0-SNAPSHOT.jar
        retention-days: 1
  
  leetcode:
    runs-on: windows-latest
    needs: build
    env:
      USERNAME: ${{ secrets.TEMP_GITHUB_PASSWORD }}
      PASSWD: ${{ secrets.TEMP_GITHUB_USERNAME }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1
      with:
        ref: ${{ github.ref }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64

    - name: Download JAR Artifact
      uses: actions/download-artifact@v4.0.0
      with:
        name: jar-artifact
        path: ./build/libs/

    - name: Run JAR Artifact
      run: java -jar ./build/libs/CMRIT2025Leaderboard-1.0-SNAPSHOT.jar load_data

    - name: Set up Python 3.10 # Set up Python version 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies # Install Python dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r src/main/python/requirements.txt

    - name: Run the program # Run the Python main.py script
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 20
        max_attempts: 10
        retry_on: error
        command: python -u src/main/python/scrape_leetcode.py

    - name: Upload LeetCode Ratings
      uses: actions/upload-artifact@v4.0.0
      with:
        name: leetcode_ratings
        path: ./leetcode_ratings.txt
        retention-days: 1

    