name: Test Run of generating Leaedrboard

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *' # Runs at 12 am and 12 pm UTC time, 5:30 AM and PM respectively

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt' # Use 'adopt' distribution on Windows
          architecture: x64

      - name: Run CLI
        run: |
          java -jar ./out/artifacts/CMRITLeaderboard2025_jar/CMRITLeaderboard2025.jar minimal
          
      - name: Archive Generated File
        run: |
          mkdir -p ${{ github.workspace }}/LeaderboardsStorage
          cp -f Leaderboards/* ${{ github.workspace }}/LeaderboardsStorage

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: leaderboard-artifact
          path: ${{ github.workspace }}/LeaderboardsStorage

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y %H:%M:%S')"

      - name: Commit Generated Excel File
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ${{ github.workspace }}/Leaderboards/*
          git commit -m "Add generated leaderboard data - ${{ steps.date.outputs.date }}"
          git push
