name: Update Leaderboard and Site
on:
  schedule:
    # Runs at this time UTC every day
    - cron: '15 06 * * *'

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17' # Use LTS version of Java unless 21 is specifically required

    - name: Compile Project
      run: javac -d ./build/classes/cmritleaderboard2025 -cp "./lib/*" cmritleaderboard2025/CMRITLeaderboard2025.java

    - name: Run Java Program
      run: java -cp "./build/classes/cmritleaderboard2025:./lib/*" cmritleaderboard2025.CMRITLeaderboard2025

    - name: Replace index.html
      run: mv -f ./index.html index.html

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add index.html Leaderboards/CMRIT2025Leaderboard.xlsx
        git commit -m "Update Leaderboard - $(date +'%Y-%m-%d %H:%M:%S')"
        git push

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Generated-index-html
        path: ./index.html
