
name: Java CI

on:
  schedule:
    # Runs at 2 AM UTC every day
    - cron: '28 21 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Setup a specific version of Java
        distribution: 'adopt' # Use 'adopt' distribution on Windows
        architecture: x64
    
    - name: Compile Project
      run: |
          javac -d bin -cp ".\lib\*" 
    
    - name: Run Java code
      run: java -jar CMRITLeaderboard2025.jar

    - name: Archive Generated File
      run: |
          mkdir -p ${{ github.workspace }}\Leaderboards
          move .\Leaderboards\CMRIT2025Leaderboard.xlsx ${{ github.workspace }}\Leaderboards

    - name: Commit HTML File
      run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ${{ github.workspace }}\index.html
          git commit -m "Add generated leaderboard data - ${{ steps.date.outputs.date }}"
          git push


    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
          name: Leaderboard
          path: ${{ github.workspace }}
