
name: Java CI

on:
  schedule:
    # Runs at 2 AM UTC every day
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Setup a specific version of Java

    - name: Run Java code
      run: java -jar CMRITLeaderboard2025.jar

    - name: Commit HTML File
      run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ${{ github.workspace }}\Leaderboards\CurrentCMRITLeaderboard2025.html
          git commit -m "Add generated leaderboard data - ${{ steps.date.outputs.date }}"
          git push


    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
          name: Leaderboard
          path: ${{ github.workspace }}\Leaderboards
