name: Update Leaderboard and Site

on:
  schedule:
    - cron: '05 18 * * *'

jobs:
  update-leaderboard:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compile Java Program
        run: javac -d build/classes -cp ".\lib\*" src\cmritleaderboard2025\*.java

      - name: Run Java Program
        run: java -cp .\build\classes;.\lib\* cmritleaderboard2025.CMRITLeaderboard2025

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add Leaderboards/CurrentCMRITLeaderboard2025.xlsx
          git add index.html
          git commit -m "Update Leaderboard - $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" || echo "No changes to commit"
          git push

      - name: Upload index.html as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-index-html
          path: index.html
