
name: Update Leaderboard and Site

on:
  schedule:
    - cron: '58 09 * * *'

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java Program
        run: javac -d build/classes -cp "./lib/*" src/cmritleaderboard2025/*.java

      - name: Run Java Program
        run: java -cp ./build/classes:./lib/* cmritleaderboard2025.CMRITLeaderboard2025

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.html Leaderboards/
          git commit -m "Update Leaderboard - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push

      - name: Upload index.html as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: generated-index-html
          path: index.html
