
name: Java CI

on:
  schedule:
    # Runs at 2 AM UTC every day
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Setup a specific version of Java

    - name: Run Java code
      run: java -jar CMRITLeaderboard2025.jar

    - name: Commit and Push Leaderboard Files
      run: |
        git config --global user.email "gabyah92@gmail.com"
        git config --global user.name "gabyah92"
        git add -A
        git commit -m "Update Leaderboard" --allow-empty
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates a GITHUB_TOKEN secret

   
