name: Python application

on:
  # Trigger the workflow manually or on push to files in src/main/resources/
  workflow_dispatch:
  schedule:
    - cron: '58 17 * * 1,4'

jobs:
  geeksforgeeks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Download Username excel sheet # Download the Username excel sheet from the Google Sheets
        run:  wget "https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vTuq5uvNpRnEXxfwPUOgSWhFZPs_0BQZV6HnV-HIqh2tovJTHVWT_moXoOTl-uejmY_bgREOaqMZ27-/pub?output=csv&gid=1214357857&single=true" -O src/main/resources/CMRIT2025Leaderboard.csv

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r usernameVerifier/requirements.txt

      - name: Run GeeksForGeeks platform
        run: |
          cd usernameVerifier
          python main.py geeksforgeeks

      - name: Archive logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: usernameVerifier/log.txt
          compression-level: 9
          retention-days: 5

  codeforces:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Download Username excel sheet # Download the Username excel sheet from the Google Sheets
        run:  wget "https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vTuq5uvNpRnEXxfwPUOgSWhFZPs_0BQZV6HnV-HIqh2tovJTHVWT_moXoOTl-uejmY_bgREOaqMZ27-/pub?output=csv&gid=1214357857&single=true" -O src/main/resources/CMRIT2025Leaderboard.csv

      - name: Set up Python 3.10 # Set up Python version 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies # Install Python dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r usernameVerifier/requirements.txt

      - name: Run Codeforces script # Run the Python script for Codeforces
        run: |
          cd usernameVerifier
          python main.py codeforces

      - name: Archive Codeforces logs # Archive the logs generated by the Codeforces script
        uses: actions/upload-artifact@v4
        with:
          name: codeforces-logs
          path: usernameVerifier/codeforces.log
          compression-level: 9
          retention-days: 5

  leetcode:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Download Username excel sheet # Download the Username excel sheet from the Google Sheets
        run:  wget "https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vTuq5uvNpRnEXxfwPUOgSWhFZPs_0BQZV6HnV-HIqh2tovJTHVWT_moXoOTl-uejmY_bgREOaqMZ27-/pub?output=csv&gid=1214357857&single=true" -O src/main/resources/CMRIT2025Leaderboard.csv

      - name: Set up Python 3.10 # Set up Python version 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies # Install Python dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r usernameVerifier/requirements.txt

      - name: Run LeetCode script # Run the Python script for LeetCode
        run: |
          cd usernameVerifier
          python main.py leetcode

      - name: Archive LeetCode logs # Archive the logs generated by the LeetCode script
        uses: actions/upload-artifact@v4
        with:
          name: leetcode-logs
          path: usernameVerifier/leetcode.log
          compression-level: 9
          retention-days: 5


  codechef:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Download Username excel sheet # Download the Username excel sheet from the Google Sheets
        run:  wget "https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vTuq5uvNpRnEXxfwPUOgSWhFZPs_0BQZV6HnV-HIqh2tovJTHVWT_moXoOTl-uejmY_bgREOaqMZ27-/pub?output=csv&gid=1214357857&single=true" -O src/main/resources/CMRIT2025Leaderboard.csv

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r usernameVerifier/requirements.txt

      - name: Run CodeChef processing
        run: |
          cd usernameVerifier
          python main.py codechef

      - name: Archive logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: usernameVerifier/log.txt
          compression-level: 9
          retention-days: 5

  hackerrank:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Download Username excel sheet # Download the Username excel sheet from the Google Sheets
        run:  wget "https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vTuq5uvNpRnEXxfwPUOgSWhFZPs_0BQZV6HnV-HIqh2tovJTHVWT_moXoOTl-uejmY_bgREOaqMZ27-/pub?output=csv&gid=1214357857&single=true" -O src/main/resources/CMRIT2025Leaderboard.csv

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r usernameVerifier/requirements.txt

      - name: Run HackerRank processing
        run: |
          cd usernameVerifier
          python main.py hackerrank

      - name: Archive logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: usernameVerifier/log.txt
          compression-level: 9
          retention-days: 5


  combine:
    runs-on: ubuntu-latest
    needs: [geeksforgeeks, codeforces, leetcode, codechef, hackerrank]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r usernameVerifier/requirements.txt

      - name: Run combine option
        run: |
          cd usernameVerifier
          python main.py combine

  push-changes:
    runs-on: ubuntu-latest
    needs: [combine]
    steps:
      - name: Get the current date
        id: date
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Commit Generated Excel File
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add src/main/resources/participant_details.csv
          git commit -m "Add generated Verification data - $NOW"
          git push
