# This workflow will install Python dependencies, run tests, and lint with a single version of Python
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  # Trigger the workflow manually or on push to files in src/main/resources/
  workflow_dispatch:
  schedule:
    - cron: '58 17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1 # Checkout the repository's code

    - name: Download CSV File
      run: wget -O "src/main/resources/CMRIT2025Leaderboard.xlsx" "https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vTuq5uvNpRnEXxfwPUOgSWhFZPs_0BQZV6HnV-HIqh2tovJTHVWT_moXoOTl-uejmY_bgREOaqMZ27-/pub?output=csv&gid=1214357857&single=true"

    - name: Set up Python 3.10 # Set up Python version 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies # Install Python dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r usernameVerifier/requirements.txt

    - name: Run the program # Run the Python main.py script
      run: |
        cd usernameVerifier
        python main.py

    - name: Archive logs # Archive the logs generated by the Python script
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: usernameVerifier/log.txt
        compression-level: 9
        retention-days: 5

    - name: Get the current date
      id: date
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    - name: Commit Generated Excel File # Commit the generated Excel file and log with a timestamp
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add src/main/resources/participant_details.csv
        git commit -m "Add generated Verification data - $NOW"
        git push --force # Push the changes forcefully
